---

- hosts: all
  become: true
  tasks:

  - name: Install apache and PHP for Debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: Install apache and PHP for CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
