---

- hosts: all
  become: true
  pre_tasks:

    - name: Install update (CentOS)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Install update (Debian)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Debian"


- hosts: workstations
  become: true
  tasks:

  - name: Install unzip
    apt:
      name: unzip
      state: latest

  - name: Install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.15.8/terraform_1.15.8_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: web_servers
  become: true
  tasks:

  - name: Install apache and PHP for Debian
    tags: apache,apache2,debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"

  - name: Install apache and PHP for CentOS
    tags: apache,httpd,centos
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: Change E-mail address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: Restart httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: Copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb package (CentOS)
    tags: db,mariadb,centos
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Install mariadb package (Debian)
    tags: db,mariadb,debian
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"


- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    tags: samba
    package:
      name: samba
      state: latest
